config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get 'comments/index'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy, :index]
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :from_messages, class_name: "Message",
                            foreign_key: "from_id",
                            dependent: :destroy
  has_many :to_massages, class_name: "Message",
                         foreign_key: "to_id",
                         dependent: :destroy

  has_many :sent_messages, through: :from_messages, source: :to
  has_many :received_messages, through: :to_messages, source: :from
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
             format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  mount_uploader :image, ImageUploader


  def feed
    following_ids="select followed_id from relationships where follower_id=:user_id"
    Micropost.where("user_id  IN (#{following_ids}) OR user_id =:user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す

  def  User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
     digest=send("#{attribute}_digest")
     return false if digest.nil?
     BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now )
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token= User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)

  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hour.ago
  end

  # Send message to other user
 def send_message(other_user, room_id, content)
   from_messages.create!(to_id: other_user.id, room_id: room_id, content: content)
 end

   private
    # メールアドレスをすべて小文字にする
    def downcase_email
       self.email.downcase!
    end

    # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #logged_in_userはこのファイルに書いたメソッド名
 before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]

 before_action :correct_user, only: [:edit, :update]

 before_action :admin_user, only: :destroy


  def index

    @users=User.where(activated: true).paginate(page: params[:page], per_page: 30)

  end

  def new

    @user = User.new

  end

  def show


    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @room_id = message_room_id(current_user, @user)
    @messages = Message.recent_in_room(@room_id)
    redirect_to root_url and return unless @user.activated?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
     UserMailer.account_activation(@user).deliver_now
     flash[:info] = "Please check your email to activate your account."
     redirect_to root_url
    else
     render "new"
    end
  end

  def edit
  end

  def update
   if @user.update_attributes(user_params)
     flash[:success]= "Profile updated"
     redirect_to @user

     #更新に成功した場合を扱う
   else
    render 'edit'
   end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end


 def following
   @title="Following"
   @user=User.find(params[:id])
   @users=@user.following.paginate(page: params[:page])
   render 'show_follow'
 end

 def followers
  @title="Followers"
  @user = User.find(params[:id])
  @users = @user.followers.paginate(page: params[:page])
  render 'show_follow'
 end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end





 def correct_user
   @user=User.find(params[:id])
   redirect_to(root_url) unless current_user?(@user)
 end

 def admin_user
   redirect_to(root_url) unless current_user.admin?
 end

 def message_room_id(first_user, second_user)
  first_id = first_user.id.to_i
  second_id = second_user.id.to_i
  if first_id < second_id
    "#{first_user.id}-#{second_user.id}"
  else
    "#{second_user.id}-#{first_user.id}"
  end
end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f|%>
<%= render "shared/error_messages", object: f.object%>

<%= f.label :name, class: 'form_control'%>
<%= f.text_field :name, class: 'form-control'%>

<%= f.label :email%>
<%=f.email_field :email, class: 'form-control'%>

<%= f.label :password%>
<%= f.password_field :password, class: "form-control"%>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmatino, class: "form-control" %>

<%= f.label :image, "イメージ画像"%>
<%= f.file_field :image, class: "form-control"%>
<%= f.submit yield(:button_text), class: "btn btn-primary"%>
<% end%>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
 <li>
   <%= link_to user.name, user_path(user) %>
   <div><%= link_to image_tag("#{user.image}", {:size =>'100x80', :alt => ""}), user%></div>
   <% if current_user.admin? && !current_user?(user) %>

| <%= link_to "delete", user, method: :delete,
                                 data: { confirm: "You sure?" } %>
 <% end %>

 </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user")%>
<% provide(:url, user_path(@user))%>
<% provide(:button_text, "Save changes")%>

<h1>Update your profile</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
<%= render "form"%>
 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users")%>

<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
 <%= render @users%>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:url, signup_path)%>
<% provide(:button_text, "Create my account")%>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render "form"%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <h1><%= link_to image_tag("#{@user.image}", {:size =>'300x300', :alt => ""}), @user%></h1>
        <h1><%= @user.name %></h1>
        <%=  @user%>
        <%= @room_id%>
    </section>
    <section class="stats">
       <%= render 'shared/stats' %>
    </section>
    <% if !current_user?(@user) && logged_in? %>
   <section class="message_box">
     <div id="messages">
       <%= render @messages %>
     </div>
   </section>
   <script type="text/javascript">
     var height = 0;
     $("div.message").each( function() {
       height += ($(this).height());
     });
     $('section.message_box').scrollTop(height);
   </script>
   <div class="message_form">
    <%= render 'messages/message_form',
      {from_user: current_user, to_user: @user, room_id: @room_id} %>
   </div>
 <% end %>
    </aside>
    <div class="col-md-8">
      <%= render "follow_form" if logged_in?%>
   <% if @user.microposts.any? %>
     <h3>Microposts (<%= @user.microposts.count %>)</h3>
     <ol class="microposts">
       <%= render @microposts %>
     </ol>
     <%= will_paginate @microposts %>
   <% end %>
 </div>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title)%>
 <div class="row">
   <aside class="col-md-4">
     <section class="user_info">
       <%= image_tag("#{@user.image}", {:alt => '新規登録', :size =>'200x200'})%>
       <h1><%= @user.name%></h1>
       <span><%= link_to "view my pofile", @user %></span>
       <span><b>Microposts:</b><%= @user.microposts.count%></span>
     </section>
     <section class="stats">
       <%= render "shared/stats"%>
        <% if @users.any?%>
         <div class="user_avatas">
           <% @users.each do |user|%>
            <%= link_to image_tag("#{user.image}", {alt: "no", size: "30x30"}), user%>
           <% end%>
         </div>
        <% end%>
     </section>
   </aside>
   <div class="col-md-8">
     <h3><%= @title%><h3>
       <% if @users.any?%>
       <ul class="users follow">
         <%= render @users%>
       </ul>
       <%= will_paginate%>
      <% end%>
   </div>